"""Calibrate effective toxin potencies to the literature cytotoxicity anchors.

For a single-target toxin the emergent cytotoxic IC50 scales linearly with the
target's potency constant (occupancy depends only on dose/ic50), and scaling all
targets of a multi-target toxin together shifts the whole dose-response by the
same factor. So calibration is a one-shot multiplicative solve per toxin:

    new_scale = old_scale * (reference_ic50 / model_ic50)

Results are written to data/reference/calibration.yaml as a potency-scale overlay
(the authored YAMLs are left untouched).
"""

from __future__ import annotations

from dataclasses import dataclass

import yaml

from ..experiments.screen import dose_response
from ..model.registry import (
    CALIBRATION_FILE,
    _calibration,
    clear_caches,
    load_all_toxins,
    load_cell,
)
from .reference import load_references


@dataclass
class CalibrationResult:
    toxin: str
    old_scale: float
    new_scale: float
    model_ic50_before: float
    reference_ic50: float


def compute_calibration(duration_h: float = 24.0) -> list[CalibrationResult]:
    toxins = load_all_toxins()
    current = _calibration()
    results: list[CalibrationResult] = []

    for ref in load_references():
        if ref.toxin not in toxins:
            continue
        cell = load_cell(ref.cell)
        dr = dose_response(toxins[ref.toxin], cell, toxins, duration_h=duration_h)
        if dr.ic50 is None or dr.ic50 <= 0:
            continue  # cannot calibrate a toxin with no cytotoxic IC50 (e.g. BSO)
        old = current.get(ref.toxin, 1.0)
        new = old * (ref.ic50_uM / dr.ic50)
        results.append(
            CalibrationResult(
                toxin=ref.toxin, old_scale=old, new_scale=new,
                model_ic50_before=dr.ic50, reference_ic50=ref.ic50_uM,
            )
        )
    return results


def apply_calibration(results: list[CalibrationResult]) -> None:
    payload = {"potency_scale": {r.toxin: round(r.new_scale, 6) for r in results}}
    CALIBRATION_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(CALIBRATION_FILE, "w", encoding="utf-8") as fh:
        fh.write(
            "# Auto-generated by `celltwin calibrate`. Per-toxin effective-potency\n"
            "# scale factors that align model cytotoxic IC50 with data/reference/\n"
            "# cytotoxicity.yaml. Re-derivable; do not edit by hand.\n"
        )
        yaml.safe_dump(payload, fh, sort_keys=True)
    clear_caches()
